project_name: compromised

builds:
  - main: ./cmd/compromised

    binary: compromised

    flags:
      - -v
      - -trimpath

    ldflags:
      - -s -w -X resenje.org/compromised.version={{.Version}}

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - '386'
      - arm64
      - arm

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"

    format: binary
